otchoo/classy

app/controllers/users/registrations_controller.rb, app/models/user.rb, app/views/devise/sessions/new.html.erb, config/initializers/devise.rb, config/locales/models/en.yml, config/locales/views/en.yml
Task 4.1: Login by username/email and password
=> Login by username/email and password

Gemfile, Gemfile.lock, app/controllers/home_pages_controller.rb, app/controllers/training_centers_controller.rb, app/models/concerns/friendly_find.rb, app/models/concerns/friendly_url.rb, app/models/training_center.rb, app/views/home_pages/index.html.erb, app/views/training_centers/show.html.erb, config/routes.rb, db/migrate/20171009203742_add_slug_into_training_centers.rb, db/schema.rb
Task 8.1: Show training center home page
=> Task 8.1: Show training center home page

app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/home_pages/index.html.erb, config/locales/views/en.yml
Task | Content
-- | --
4.4 | Go to forgot password page
5.1 | Create forgot password request
5.2 | Create new password from reset password token
6.5 | Goto login page if not sign in
6.6 | Logout if user signed in
=> Forgot password request/change

app/controllers/branches_controller.rb, app/models/branch.rb, app/views/branches/_branch.html.erb, app/views/branches/show.html.erb, app/views/training_centers/show.html.erb, config/locales/views/en.yml, config/routes.rb, db/migrate/20171012134053_add_slug_to_branches.rb, db/schema.rb
Tasks are completed: 
8.2: Training center page - Go to its branches page
9.4: Traing center - branches page - Go to branch page
11.1: View branch home page
11.2: Branch page - Go to training center page
=> Task 11.1: View branch page

app/assets/stylesheets/map.scss, app/views/branches/show.html.erb, app/views/shared/google_map/_branch_map.html.erb, app/views/shared/google_map/_branch_map.js.erb, config/settings.yml
=> Task 11.5 View branch on map

app/controllers/home_pages_controller.rb, app/controllers/my_page/account_informations_controller.rb, app/controllers/my_page/base_controller.rb, app/controllers/my_page/personal_informations_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/home_pages/index.html.erb, app/views/my_page/account_informations/edit.html.erb, app/views/my_page/personal_informations/edit.html.erb, app/views/users/show.html.erb, config/locales/views/en.yml, config/locales/views/my_page.yml, config/routes.rb, db/seeds.rb
Task | Content
-- | --
13.1 | Show user profile
14.1 | Update personal information
15.1 | Update account information
=> 13.1	Show user profile 	 14.1	Update personal information 15.1	Update account information

app/decorators/comment_decorator.rb, app/policies/user_policy.rb, app/views/shared/comments/_comment.html.erb, app/views/shared/reviews/_review.html.erb, app/views/users/show.html.erb, db/seeds.rb
Task | Content
-- | --
12.7 | Go to user page via review
12.8 | Go to user page via comment
=> Task 12.7	 + Task 12.8 Display Owner name on comment/review

app/controllers/comments_controller.rb, app/policies/center_comment_policy.rb, app/policies/user_comment_policy.rb, app/views/comments/destroy.js.erb, app/views/shared/comments/_comment.html.erb, config/locales/views/en.yml, config/routes.rb
=> Task 12.14 Delete own comment

app/assets/javascripts/comment.js, app/controllers/comments_controller.rb, app/policies/center_comment_policy.rb, app/policies/user_comment_policy.rb, app/views/comments/edit.js.erb, app/views/comments/update.js.erb, app/views/shared/comments/_comment.html.erb, app/views/shared/comments/_edit_comment.html.erb, config/routes.rb
=> Task 12.13	Edit own comment

app/controllers/my_page/passwords_controller.rb, app/models/user.rb, app/views/my_page/account_informations/edit.html.erb, app/views/my_page/passwords/edit.html.erb, app/views/users/show.html.erb, config/locales/views/my_page.yml, config/routes.rb
Task#16.1 User update password
=> Task#16.1 User update password

app/controllers/application_controller.rb, app/controllers/reports_controller.rb, app/models/comment.rb, app/models/report.rb, app/models/review.rb, app/models/user.rb, app/policies/review_policy.rb, app/views/branch/reviews/index.html.erb, app/views/branch/reviews/index.js.erb, app/views/center/reviews/index.html.erb, app/views/center/reviews/index.js.erb, app/views/reports/create.js.erb, app/views/reports/new.js.erb, app/views/shared/reports/_report_form.html.erb, app/views/shared/reports/_report_modal.html.erb, app/views/shared/reviews/_review.html.erb, config/locales/views/en.yml, config/routes.rb, config/settings.yml, db/migrate/20171113022118_create_reports.rb, db/schema.rb, spec/models/report_spec.rb
task#12.15	Create report review
=> task#12.15	Create report review

app/policies/center_policy.rb, app/views/centers/show.html.erb, config/locales/views/en.yml
Task | content 
-- | -- 
8.4   |   Go to edit training center if user is owner
=> Task#8.4      Go to edit training center if user is owner

app/controllers/my_page/reports_controller.rb, app/controllers/reports_controller.rb, app/decorators/report_decorator.rb, app/models/comment.rb, app/models/report.rb, app/policies/center_policy.rb, app/policies/report_policy.rb, app/views/my_page/reports/_report.html.erb, app/views/my_page/reports/destroy.js.erb, app/views/my_page/reports/index.html.erb, app/views/users/show.html.erb, config/locales/views/en.yml, config/locales/views/my_page.yml, config/routes.rb, config/settings.yml, db/migrate/20171121093955_add_column_deleted_at_to_reports.rb, db/schema.rb
Task 18.1, 18.2	My page - View list report, filter report
=> Task 18.1, 18.2, 18.3	My page - View list report, filter report, delete report

app/models/center.rb, app/policies/center_comment_policy.rb, app/policies/center_policy.rb, app/policies/review_policy.rb, app/policies/user_comment_policy.rb, app/views/centers/show.html.erb, app/views/shared/comments/_comment.html.erb, config/locales/views/en.yml
Task | content 
-- | -- 
8.5 | Create report center 
10.7 | Create comment report 
11.7 | Create report branch
=> Task 8.5 10.7 11.7 create report for comment, branch, center

public/mock/css/base.less, public/mock/css/modules/_reviews.less, public/mock/reviews.html
=> add comment button

public/mock/css/base.less, public/mock/css/common.less, public/mock/css/modules/_modal_review.less, public/mock/js/review.js, public/mock/reviews.html
=> Create modal new review

public/mock/css/base/base.less, public/mock/css/common.less, public/mock/css/modules/_form.less, public/mock/login.html, vendor/assets/frontend/sass/base/_base.scss
=> custom form

app/assets/javascripts/application.js, app/assets/javascripts/navbar.js, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/navbar.scss, app/views/layouts/application.html.erb, app/views/layouts/center.html.erb, app/views/layouts/shared/_header.html.erb, public/mock/css/common.less, public/mock/css/modules/_navbar.less, public/mock/navbar_guest.html, public/mock/navbar_member.html, vendor/assets/fonts/css/google_fonts.css
Design navbar, stick navbar on top
=> stick navigation ontop

public/mock/courses.html, public/mock/css/base/_variables.less, public/mock/css/base/base.less
=> mock course page

public/mock/css/base/_variables.less, public/mock/css/base/base.less, public/mock/css/modules/_navbar.less, public/mock/css/modules/_reviews.less, public/mock/js/common.js, public/mock/reviews.html
=> add report button

public/mock/css/base/_variables.less, public/mock/css/base/base.less
=> hotfix select box

app/assets/stylesheets/navbar.scss
=> fix navbar header hidden

public/mock/account.html, public/mock/css/common.less, public/mock/css/modules/_user.less, public/mock/personal.html, public/mock/profile.html
=> Mock user profile

app/assets/javascripts/admin/application.js, app/assets/stylesheets/admin/application.css, app/assets/stylesheets/admin/custom.scss, app/controllers/admin/base_controller.rb, app/controllers/admin/reports_controller.rb, app/decorators/application_decorator.rb, app/decorators/report_decorator.rb, app/helpers/report_helper.rb, app/models/report.rb, app/models/user.rb, app/policies/application_policy.rb, app/policies/report_policy.rb, app/views/admin/reports/_report.html.erb, app/views/admin/reports/_report_filter.html.erb, app/views/admin/reports/_response_report_form.html.erb, app/views/admin/reports/_response_report_modal.html.erb, app/views/admin/reports/edit.js.erb, app/views/admin/reports/index.html.erb, app/views/admin/reports/update.js.erb, app/views/layouts/admin.html.erb, app/views/layouts/admin/_sidebar.html.erb, config/locales/views/en.yml, config/routes/admin.rb, config/settings.yml, vendor/assets/frontend/sass/base/_base.scss
Task-50 Admin manage reports (view, filter, review)
=> Task-50 Admin manage reports (view, filter, review)

app/controllers/admin/base_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/application_controller.rb, app/helpers/user_helper.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/admin/users/_user.html.erb, app/views/admin/users/_user_filter.html.erb, app/views/admin/users/index.html.erb, app/views/admin/users/new.html.erb, app/views/layouts/admin/_sidebar.html.erb, config/routes/admin.rb, config/settings.yml
=> admin manage user

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/custom.scss, app/views/layouts/shared/_footer.html.erb, config/locales/views/vi.yml
=> add footer

app/controllers/home_pages_controller.rb, app/views/home_pages/business.html.erb, app/views/home_pages/index.html.erb, app/views/layouts/full_page.html.erb, app/views/layouts/shared/_header.html.erb, config/routes.rb
=> add index-page, business page

app/views/center/reviews/_rating_criterion_avarage.html.erb, app/views/center/reviews/_review_statistics.html.erb, app/views/layouts/center/_center_details.html.erb, app/views/layouts/center/_criterion_avarage_rating.html.erb, config/locales/models/vi.yml, config/locales/views/vi.yml
=> add i18n 20/12

app/assets/stylesheets/custom.scss, app/views/center/reviews/_branch_filter.html.erb, app/views/review/comments/create.js.erb, app/views/shared/reviews/_new_comment.html.erb, config/locales/views/vi.yml
=> fix i18n 21/12

app/assets/stylesheets/custom.scss, app/views/layouts/management/_sidebar.html.erb, app/views/management/branches/_form.html.erb, app/views/management/branches/index.html.erb, app/views/management/centers/_form.html.erb, app/views/management/centers/edit.html.erb, app/views/management/courses/_course.html.erb, app/views/management/courses/_form.html.erb, app/views/management/courses/edit.html.erb, app/views/management/courses/index.html.erb, app/views/management/dashboards/show.html.erb, app/views/management/verification/reviews/_filter.html.erb, app/views/management/verification/reviews/_review.html.erb, app/views/management/verification/reviews/index.html.erb, config/locales/models/vi.yml, config/locales/views/vi.yml
=> hot fix i18n

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, config/initializers/carrierwave.rb, config/locales/views/admin.vi.yml, config/routes/admin.rb, config/sidekiq.yml
=> hot fix wired slow
